__title__ = "chromhmm-pipeline"
__version__ = "0.1.0"
__description__ = "Python scripts required for running ENCODE ChromHMM pipeline."
__url__ = "https://github.com/ENCODE-DCC/chromhmm-pipeline"
__uri__ = __url__
__author__ = "Paul Sud"
__email__ = "encode-help@lists.stanford.edu"
__license__ = "MIT"
__copyright__ = "Copyright (c) 2021 ENCODE DCC"
