---
version: 2.1
defaults: &defaults
  docker:
    - image: circleci/buildpack-deps:xenial-scm
  working_directory: ~/chromhmm-pipeline

commands:
  make_tag:
    description: Make docker image tag
    steps:
      - run: echo "export TAG=quay.io/encode-dcc/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_BRANCH}_${CIRCLE_WORKFLOW_ID}" > ${BASH_ENV}

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - make_tag
      - run:
          name: build image
          command: |
            source ${BASH_ENV}
            echo "pulling template!"
            docker pull quay.io/encode-dcc/chromhmm-pipeline:template
            docker login -u=${QUAY_ROBOT_USER} -p=${QUAY_ROBOT_USER_TOKEN} quay.io
            docker build --cache-from quay.io/encode-dcc/chromhmm-pipeline:template --build-arg GIT_COMMIT_HASH=${CIRCLE_SHA1} --build-arg BRANCH=${CIRCLE_BRANCH} --build-arg BUILD_TAG=${TAG} -t $TAG .
             docker push $TAG
             docker logout
          no_output_timeout: 30m

  push_template:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - make_tag
      - run:
          command: |
            source ${BASH_ENV}
            docker pull $TAG
            docker login -u=${QUAY_ROBOT_USER} -p=${QUAY_ROBOT_USER_TOKEN} quay.io
            docker tag $TAG quay.io/encode-dcc/chromhmm-pipeline:template
            docker push quay.io/encode-dcc/chromhmm-pipeline:template
            docker logout
          no_output_timeout: 30m

# Workflow
workflows:
  build_workflow:
    jobs:
      - build
      - push_template:
          requires:
            - build
